### ISSUE TITLE
Weird error on windows

### ISSUE THREAD

**Issue by VerioN1** [hschimke/rxing-wasm#4]
I have a project running with rxing-wasm on my mac and worked fine. But when I wanted to move to windows - running the same code that works on mac - gives me this error
![image](https://user-images.githubusercontent.com/15872957/222920982-28cb6591-5c19-427d-845a-93f0368cf969.png)

this is the code I was trying to run: 

`	const ctx = canvas.getContext('2d');
	if (!ctx) {
		throw 'no context';
	}
	const imageData = ctx.getImageData(0, 0, canvas.width, canvas.height);
	try {
		// @ts-ignore
		const luma_data = convert_js_image_to_luma(imageData.data);
		const hints = new DecodeHintDictionary();
		hints.set_hint(DecodeHintTypes.PossibleFormats, 'UpcEanExtension');
		hints.set_hint(DecodeHintTypes.TryHarder, 'true');
		const result = decode_barcode_with_hints(luma_data, canvas.width, canvas.height, hints);
		console.warn(result.text());
	} catch (e) {
		console.log(e);
	}
`

**Comment by hschimke** [comment]
I'll look into this. I mostly use a Mac too, but I'll set it up on my windows box and try to replicate.

**Comment by hschimke** [comment]
Which node version are you using, and which version of rxing-wasm?

**Comment by hschimke** [comment]
Is this when you run a vite build? I can get a svelte kit app running with vite dev server which won't build for deployment with roughly the same error. 

Looks like a vite problem, but I see some workarounds when building the package that might fix it.

**Comment by VerioN1** [comment]
can you tell me what it is?
I am using node 16 and latest of rxing-wasm.
when in running development on windows I get this error

**Comment by hschimke** [comment]
Looks like this error: https://github.com/Menci/vite-plugin-wasm/issues/26

This is the other thing that I was looking at: https://stackoverflow.com/questions/72587871/how-to-include-an-wasm-npm-module-in-svelte-with-vite

Note: I tried their suggestion for adding a main property and it did not resolve any issues (on linux).

This is the other plugin that might work, but again the require that the plugin be built with type=web, which currently isn't the case: https://github.com/nshen/vite-plugin-wasm-pack/

**Comment by hschimke** [comment]
If `3.2.2` of the plugin fixes your issue, I pushed a new version of rxing-wasm (`0.1.16` on npm) that includes the correct "type" and "main" properties in the package.json file.

As Menci suggests, you might have to add `NODE_OPTIONS=--experimental-wasm-modules` to your build command (I did, at least for svelte-kit).

**Comment by VerioN1** [comment]
so as of now, you cannot run dev any project that includes this module on windows am I right?
this plugin didn't help

**Comment by VerioN1** [comment]
never mind. upgrading vite-plugin-wasm to 3.2.2 fixed the issue.
