### ISSUE TITLE
"Uncaught RuntimeError: unreachable executed" errors

### ISSUE THREAD

**Issue by thisisaaronland** [hschimke/rxing-wasm#5]
Hi,

My knowledge of Rust and of WebAssembly internals is still pretty shallow so apologies in advance if I am missing something obvious. I am trying to use the `rxing-wasm` package as bundled by the `wasm-pack build` command described here:

https://www.furidamu.org/blog/2020/07/10/rust-webassembly-in-the-browser/

That seems to work fine and I am able to initialize the resultant WASM binary and invoke the `convert_js_image_to_luma` function but when I try to call `decode_barcode` it panics with the following error:

```
Uncaught RuntimeError: unreachable executed
    decode_barcode http://localhost:8080/rxing_wasm.js:187
    onload http://localhost:8080/?:43
    onclick http://localhost:8080/?:30
    main http://localhost:8080/?:24
    async* http://localhost:8080/?:54
[rxing_wasm_bg.wasm:1171526:1](http://localhost:8080/rxing_wasm_bg.wasm)
    __rust_start_panic http://localhost:8080/rxing_wasm_bg.wasm:1171526
    rust_panic http://localhost:8080/rxing_wasm_bg.wasm:1157051
    hc53aea0352e77326 http://localhost:8080/rxing_wasm_bg.wasm:1006605
    ha183a8279614f03a http://localhost:8080/rxing_wasm_bg.wasm:1062504
    hc33870f333461503 http://localhost:8080/rxing_wasm_bg.wasm:1154372
    rust_begin_unwind http://localhost:8080/rxing_wasm_bg.wasm:1116658
    hf4a9df75710ece83 http://localhost:8080/rxing_wasm_bg.wasm:1147033
    h8c0b59521a475ac0 http://localhost:8080/rxing_wasm_bg.wasm:1085500
    hac996b83e550b52f http://localhost:8080/rxing_wasm_bg.wasm:624364
    he1247e4575455453 http://localhost:8080/rxing_wasm_bg.wasm:746459
    hc2a7bc7f939092d4 http://localhost:8080/rxing_wasm_bg.wasm:882929
    hf770383115561eeb http://localhost:8080/rxing_wasm_bg.wasm:947342
    <rxing::qrcode::qr_code_reader::QRCodeReader as rxing::reader::Reader>::decode_with_hints::h004a4523f4768536 http://localhost:8080/rxing_wasm_bg.wasm:389867
```

I have been testing this with a PDF417 barcode image that can be successfully decoded using the `rxing-cli` tool.  All the code in question can be found here:

https://github.com/sfomuseum/rust-rxing-wasm/blob/main/www/index.html

The image I've been testing with is here:

https://github.com/sfomuseum/rust-rxing-wasm/blob/main/images/deltabp.png

Whic was taken from here:

https://krebsonsecurity.com/2015/10/whats-in-a-boarding-pass-barcode-a-lot/

Do you have any thoughts on what might be happening here or what I am doing wrong?

**Comment by hschimke** [comment]
I'll look into this. I was able to decode it using the reference demo app. I'll look at the code and see if I can find what's going wrong.

**Comment by hschimke** [comment]
### I think I found the issue:

on line 41/42 of index.html :
you have:
```js
var data = context.getImageData(0, 0, w, h);
let luma8Data = convert_js_image_to_luma(data);
```

That's passing the imageData (whatever it is, maybe an ImageData object, I'm not actually sure) into the `convert_js_image_to_luma` function, which doesn't know what to do with it, so it returns an empty array. So, when you pass that empty array into the `decode_barcode` function it panics somewhere down in the library (I should probably fix that, and instead return an error, but that's a separate issue).

I changed those lines to read:
```js
var data = context.getImageData(0, 0, w, h).data;
let luma8Data = convert_js_image_to_luma(data);
```

That way you are passing the `data` element of the ImageData object into the function. That worked for me, or at least, I no longer got a panic when attempting to decode the barcode. The code as I see it doesn't do anything with the decoded barcode, but when I glanced at it everything at least looked right.

### Another Note
If you are looking to deploy a site that uses this method of bundling, you should keep in mind that the files are pretty large. I recommend compressing them, either at the web-server level, or if you are hosting them on something like Azure Static Sites, at the deploy level.

@thisisaaronland Please let me know if this works!

**Comment by hschimke** [comment]
Also: weird fact, but wanting to decode barcodes for boarding passes was one of the primary motivations of the project originally (that and shipping labels).

**Comment by thisisaaronland** [comment]
Aha! Thank you, that fixes the problem.

This is still experimental / investigatory work for us right now but the thinking is to integrate it with this:

https://millsfield.sfomuseum.org/wayfinding/flights/

I need to do some reading on the rules and conventions for the data in boarding passes because they seem to standardize on 2-letter airline codes (?) which, in an historical context like a museum, are a hot mess of re-used identifiers. We have a whole series of lookup tables and code which we've bundled as (Go) WASM binaries but they are ridiculously large so I might investigate rewriting them in Rust since it seems better about file sizes these days.

https://github.com/sfomuseum/go-sfomuseum-airfield-wasm

Or we'll just bake a static lookup table in JSON and be done with it. A lot of this work is to better understand the shape and functionalities that WASM makes possible. A PDF417 decoder is definitely one of them so thanks again for your help.
