### ISSUE TITLE
"Not found" errors decoding barcodes (that can be decoded by rxing-cli)

### ISSUE THREAD

**Issue by thisisaaronland** [hschimke/rxing-wasm#6]
Hi,

My Rust-knowledge is a little better than the last time I asked a question but it is still pretty raw so apologies if I've missed something obvious.

I have (4) barcodes all created by, and which can be decoded by, `rxing-cli` in the PDF-417, Aztec, DataMatrix and QR code formats. Copies of these barcodes can be found here:

https://github.com/sfomuseum/rs-rxing-wasm/tree/main/images

When I try to decode them using a `rxing-wasm` binary created by `wasm-pack build --target web` only the PDF-417 can be decoded. All the others fail with a "Not found" error. For example:

```
Uncaught not found [rxing_wasm.js:293:14](http://localhost:8080/rxing_wasm.js)
    decode_barcode_with_hints http://localhost:8080/rxing_wasm.js:293
    onload http://localhost:8080/:59
    (Async: EventHandlerNonNull)
    onclick http://localhost:8080/:44
    (Async: EventHandlerNonNull)
    main http://localhost:8080/:38
    AsyncFunctionNext self-hosted:810
    (Async: async)
    <anonymous> http://localhost:8080/:79
```

The code in question can be found here:

https://github.com/sfomuseum/rs-rxing-wasm/blob/main/www/index.html

I have spent some time poking around the `rxing-cli` package to see whether there are hints, or other arguments, I should be passing to the `decode_barcode` function but it doesn't seem like it? I get the same results if I call `decode_barcode` or `decode_barcode_with_hints`. I feel like I must be missing something obvious but I am having trouble seeing what. Do you have any ideas?

Thanks,

**Comment by hschimke** [comment]
I'll take a look. Without examining anything my initial guess is that it's a difference in how the images are binarized between the image crate version and the greyscale version (even those are supposed to be the same they aren't exactly the same).

**Comment by hschimke** [comment]
Interesting, I ran them all through the reference wasm client and they all worked (rxing.azule.info for now, but eventually moving to an rxing domain I own but haven't set up). I tried with and without hints and they all worked. Could you verify which version of rxing your version of rxing-wasm is building against (I'm wondering if you got stuck with a build that came out before I fixed the rotation code)?

I'll go through the code tomorrow and see if I can figure out where things are going weird.

**Comment by thisisaaronland** [comment]
I pulled `rxing-wasm` from `main` this morning and rebuilt everything from scratch but the problem is the same. I noticed that the version specified for `rxing-core` is "~0.4.3" but on GitHub the last release is "0.4.1". I don't really understand the details of how Rust handles/caches versioning so maybe that's not relevant?

```
> rustc --version
rustc 1.68.2 (9eb3afe9e 2023-03-27)
```

```
> cat Cargo.toml 
[package]
name = "rxing-wasm"
version = "0.1.19"
edition = "2021"
description = "wasm bindings for rxing to provide commong barcode operations (decode/encode)"
repository = "https://github.com/rxing-core/rxing-wasm"
license = "Apache 2.0"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook", "decode_hints"]
decode_hints = []
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasm-bindgen = "0.2.84"
js-sys = "0.3.61"

# The `console_error_panic_hook` crate provides better debugging of panics by
# logging them with `console.error`. This is great for development, but requires
# all the `std::fmt` and `std::panicking` infrastructure, so isn't great for
# code size when deploying.
console_error_panic_hook = { version = "0.1.6", optional = true }

rxing = {version = "~0.4.3", default-features = false, features = ["wasm_support"]}
#rxing = {path="../rxing", version = "~0.2.23", default-features = false, features = ["wasm_support"]}

[dev-dependencies]
wasm-bindgen-test = "0.3.34"

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
lto = "fat"
```

```
> wasm-pack --help
wasm-pack 0.11.0
```

```
> wasm-pack build ---target=web
[INFO]: 🎯  Checking for the Wasm target...
[INFO]: 🌀  Compiling to Wasm...
    Finished release [optimized] target(s) in 0.08s
[INFO]: ⬇️  Installing wasm-bindgen...
[INFO]: ✨   Done in 0.46s
[INFO]: 📦   Your wasm pkg is ready to publish at /usr/local/sfomuseum/rxing-wasm/pkg.
```

**Comment by hschimke** [comment]
The release version on GitHub is just the last time I remembered to tag one on there. Cargo is the definitive source for releases of the library, so the 0.4.3 (https://crates.io/crates/rxing) release is the correct one. All of those versions and builds look right to me as well. I'll poke around and see if I can figure out what's happening.

**Comment by hschimke** [comment]
I'm thinking there might be a bug with the library itself here. If I remove the formats hint, all 2d barcode formats besides pdf417 fail, but oned formats work without issue.

**Comment by hschimke** [comment]
Hmm, that theory doesn't hold water, I tested the reference client using a freshly built version and it works without issue.

I have a pretty good idea of what is happening, just not why.

The what is: for some reason only the PDF417 reader and the MultiFormatOneD reader are being used when scanning. You can kind of tell this is what is happening because you get a "Not Found" exception, which means that the library isn't panicking. If you feed in a one dimensional barcode it works fine (those are handled separately from the 2d readers).

My working theory is that wasm-pack is doing something weird when target=web is set. I'll try to take your program and build it to work with a bundler and see if that fixes it. That doesn't make any sense at all to me, but since the exact same version decodes those formats without issue when built with the bundler I'm a bit at a loss as to what else it could be.

**Comment by hschimke** [comment]
I was wrong! I think I found the issue. It has to do with the way you were drawing the image, I believe. I think it's a question of how much buffer each format needs around it.

In the index.html file you have: https://github.com/sfomuseum/rs-rxing-wasm/blob/c438e404653e6c5aec8f447dfa65c9cf3b5d586d/www/index.html#L39

I changed that to: 
```js
canvas.width = img.width;
canvas.height = img.height;
context.drawImage(img, 0, 0, img.width, img.height);
```

That seems to have fixed it. At least for me. Let me know if it works!

PS: I did end up building a bundler version of your app using web pack, if you ever need it let me know.

**Comment by thisisaaronland** [comment]
Thank you! That makes everything work as expected but what a curious issue since, at least, according to the MDN docs you shouldn't need to specify width and height:

"If not specified, the entire rectangle from the coordinates specified by sx and sy to the bottom-right corner of the image is used."

https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/drawImage

Thank you very much for your help with this. I might have figured this out on my own eventually but who know how long it would have taken...

**Comment by thisisaaronland** [comment]
Oh, I see. The issue is not setting height and width in the `drawImage` method but being explicit about the dimensions of the canvas. Anyway, thanks again!
